#!/bin/bash

spark_version="$1"
case "$spark_version" in
  "1.6"*)
    zeppelin_spark_version="1.6"
    ;;
  "2.0"*)
    zeppelin_spark_version="2.0"
    ;;
  "2.1"*)
    zeppelin_spark_version="2.1"
    ;;
  "2.2"*)
    zeppelin_spark_version="2.2"
    ;;
  "2.3"*)
    zeppelin_spark_version="2.3"
    ;;
  "2.4"*)
    zeppelin_spark_version="2.4"
    ;;
  *)
    echo "Spark version '$spark_version' not supported."
    exit 1
esac

hadoop_version="$2"
case "$hadoop_version" in
  "2.6")
    ;;
  "2.7")
    ;;
  *)
    echo "Hadoop version '$hadoop_version' not supported."
    exit 1
esac
zeppelin_hadoop_version="$hadoop_version"

zeppelin_version="$3"

oracle_instantclient_version=${4:-12.2.0.1.0}

set -e -v

mkdir -p ./oracle/linux

curl \
    -L -o oracle/linux/instantclient-sdk-linux.x64.zip \
    -s https://github.com/bumpx/oracle-instantclient/raw/master/instantclient-sdk-linux.x64-$oracle_instantclient_version.zip

curl \
    -L -o oracle/linux/instantclient-sqlplus-linux.x64.zip \
    -s https://github.com/bumpx/oracle-instantclient/raw/master/instantclient-sqlplus-linux.x64-$oracle_instantclient_version.zip

curl \
    -L -o oracle/linux/instantclient-basic-linux.x64.zip \
    -s https://github.com/bumpx/oracle-instantclient/raw/master/instantclient-basic-linux.x64-$oracle_instantclient_version.zip

curl -s http://archive.apache.org/dist/spark/spark-$spark_version/spark-$spark_version-bin-hadoop$hadoop_version.tgz | tar -xz -C .
mv spark-* spark

git clone https://github.com/apache/zeppelin.git zeppelin
cd zeppelin
git checkout $zeppelin_version
if [[ "$zeppelin_spark_version" == "2.3" ]]
then
  # https://github.com/apache/zeppelin/pull/2880
  # ./dev/change_scala_version.sh 2.11
  mvn -e clean package -DskipTests -Pbuild-distr | perl -ne 'print if $. % 10 == 1'
else
  mvn -e clean package -Pspark-$zeppelin_spark_version -Phadoop-$zeppelin_hadoop_version -DskipTests -Pbuild-distr -Pscala-2.11 | perl -ne 'print if $. % 100 == 1'
fi
cd ..
mv zeppelin/zeppelin-distribution/target/zeppelin-*.tar.gz zeppelin_dist.tar.gz
rm -rf zeppelin
tar -xzf zeppelin_dist.tar.gz
mv zeppelin-* zeppelin
